[app]
GOOGLE_API_KEY = "AIzaSyDxYtaHxu5tZMLxMPv3rcDqiZ8RCxoiPus"
MONGODB_URI = "alfre943553109@pc2ayquipaquispealfredo.lccbvfk.mongodb.net/? appName=PC2AyquipaQuispeAlfredo"
USER = "Alfredo Jefferson Ayquipa Quispe"
COHERE_API_KEY = "BnrfXoDxXun4uOANCmN2FCD8T67amTgA4JG5QQSPW"

[b2]
B2_BUCKET_NAME = "ajaqPC2"
B2_READ_KEY_ID = "005affc36d328c80000000004"
B2_READ_APPLICATION_KEY = "K005QGxQvc5K3UIfGERuqWM94bGdmc0"
B2_WRITE_KEY_ID = "005affc36d328c80000000003"
B2_WRITE_APPLICATION_KEY = "K005zlop2ERAN5Tbmbnu1cKRidu4nx8"
